#!/usr/bin/perl -w

# Generate vectors.S for 64 bit x86 arch, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

print "//generated by interrupt_routines.pl - do not edit\n";
for(my $i = 0; $i < 256; $i++){
    print "void isr_handler_$i(){\n";
    print "write_string_serial(\"Exception $i Occurred\");\n";
    print "}\n\n";

}
