#!/usr/bin/perl -w

# Generate vectors.S for 64 bit x86 arch, the trap/interrupt entry points.
# There has to be one entry point per interrupt number
# since otherwise there's no way for trap() to discover
# the interrupt number.

print ";generated by interrupts.pl - do not edit\n";
for(my $i = 0; $i < 256; $i++){
    print "global isr_wrapper_$i\n";
    print "isr_wrapper_$i:\n";
    print "  pushaq \n";
    print "  call isr_routine_$i\n";
    print "  popaq \n";
    print "  iretq \n";
}

print "\n# isr_routine_table table\n";
print "routines:\n";
for(my $i = 0; $i < 256; $i++){
    print "  extern isr_routine_$i\n";
}