#!/usr/bin/perl -w
print ";generated by interrupts.pl - do not edit\n";
for(my $i = 0; $i < 256; $i++) {
    print "global irq_wrapper_$i\n";
    print "irq_wrapper_$i:\n";
    print "  pushaq \n";
    print "  mov rdi, $i\n";
    print "  push rdi \n";
    print "  call irq_handler\n";
    print "  popaq \n";
    print "  pop rdi \n";
    print "  iretq \n";
    print "        \n";
}

